In [1]:
import torch

In [2]:
# criando uma matriz tensor com 2 linhas e 4 colunas
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
print(x.shape)

torch.Size([2, 4])


In [3]:
#multiplica todos os valores por 10
x*10

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

In [4]:
# soma 10 a todos os valores
x.add(10)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

In [5]:
x

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [6]:
x.shape

torch.Size([2, 4])

In [7]:
# modificar o formato do tensor
x.view(4,2)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [8]:
# modificar o formato para uma só coluna
x.view(8,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])

In [9]:
# 2 'pilhas' cada uma com uma linha e 10 colunas
a = torch.ones(2, 1, 10)
a

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [10]:
# juntando as duas pilhas em um objeto só, com duas linhas e 10 colunas agora
squeezed = a.squeeze(1)
a.shape, squeezed.shape

(torch.Size([2, 1, 10]), torch.Size([2, 10]))

In [11]:
# dois stacks com 2 linhas e 10 colunas cada
a = torch.ones(2,2,10)
print(f'a = {a}')
print(f'Formato de a = {a.shape}')

a = tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])
Formato de a = torch.Size([2, 2, 10])


In [12]:
# não muda nadaa
squeezed = a.squeeze(1)
print(f'squeezed = {squeezed}')
print(f'Formato de squeezed = {squeezed.shape}')

squeezed = tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])
Formato de squeezed = torch.Size([2, 2, 10])


In [13]:
# dois stacks com 3 linhas e uma coluna cada
a = torch.ones(2,3,1)
print(f'a = {a}')
print(f'Formato de a = {a.shape}')

a = tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]])
Formato de a = torch.Size([2, 3, 1])


In [14]:
# aqui sim alterou para apenas 1 stack
squeezed = a.squeeze(2)
print(f'squeezed = {squeezed}')
print(f'Formato de squeezed = {squeezed.shape}')

squeezed = tensor([[1., 1., 1.],
        [1., 1., 1.]])
Formato de squeezed = torch.Size([2, 3])


In [15]:
# 2 linhas e 3 colunas
a = torch.ones(2,3)
print(f'a = {a}')
print(f'Formato de a = {a.shape}')

# alterando para 2 stacks com 3 linhas e 1 coluna
squeezed = a.unsqueeze(2)
print(f'squeezed = {squeezed}')
print(f'Formato de squeezed = {squeezed.shape}')

a = tensor([[1., 1., 1.],
        [1., 1., 1.]])
Formato de a = torch.Size([2, 3])
squeezed = tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]])
Formato de squeezed = torch.Size([2, 3, 1])


In [16]:
# 2 linhas 3 colunas
a = torch.ones(2,3)

# usando None para criar dimensões no eixo especificado
print(a[None].shape)
print(a[:,None].shape)
print(a[:,:,None].shape)

torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3, 1])


In [18]:
# matriz 2, 4
x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
# matriz 4,3
y = torch.tensor([[1, 2, 3],
                  [2, 3, 4],
                  [4, 5, 6],
                  [7, 8, 9]])

# multiplicando as 2 matrizes
torch.matmul(x, y)

tensor([[ 45,  55,  65],
        [101, 127, 153]])

In [22]:
# 1 matriz com 4 linhas e 5 colunas 
x = torch.randn(1, 4, 5)
print(f'Matriz x = {x}')

# concatenando a matriz x com outra matriz x
z = torch.cat([x, x], axis=1)
print(f'Matriz z = {z}')

Matriz x = tensor([[[-0.2505, -0.5918, -0.2564,  0.6604,  0.0757],
         [-1.2241, -0.1100,  0.9918, -0.2181, -0.0625],
         [-1.7355,  0.2666,  0.6390,  0.0078, -0.5954],
         [-1.0056,  0.4633,  1.5161,  0.4286,  0.7045]]])
Matriz z = tensor([[[-0.2505, -0.5918, -0.2564,  0.6604,  0.0757],
         [-1.2241, -0.1100,  0.9918, -0.2181, -0.0625],
         [-1.7355,  0.2666,  0.6390,  0.0078, -0.5954],
         [-1.0056,  0.4633,  1.5161,  0.4286,  0.7045],
         [-0.2505, -0.5918, -0.2564,  0.6604,  0.0757],
         [-1.2241, -0.1100,  0.9918, -0.2181, -0.0625],
         [-1.7355,  0.2666,  0.6390,  0.0078, -0.5954],
         [-1.0056,  0.4633,  1.5161,  0.4286,  0.7045]]])


In [24]:
# 3 matriz com 20 linhas e 10 colunas cada
x = torch.randn(3, 20, 10)
# permutando, ou seja, alteranndo as dimensões, invertendo elas
z = x.permute(2, 0, 1)
print(f'Dimensões alteradas: {x.shape}, {z.shape}')


Dimensões alteradas: torch.Size([3, 20, 10]), torch.Size([10, 3, 20])
