In [1]:
import torch

In [ ]:
# criando uma matriz tensor com 2 linhas e 4 colunas
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
print(x.shape)

torch.Size([2, 4])


In [ ]:
#multiplica todos os valores por 10
x*10

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

In [4]:
# soma 10 a todos os valores
x.add(10)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

In [5]:
x

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [6]:
x.shape

torch.Size([2, 4])

In [8]:
# modificar o formato do tensor
x.view(4,2)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [10]:
# modificar o formato para uma só coluna
x.view(8,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])

In [ ]:
# 2 'pilhas' cada uma com uma linha e 10 colunas
a = torch.ones(2, 1, 10)
a

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [15]:
# juntando as duas pilhas em um objeto só, com duas linhas e 10 colunas agora
squeezed = a.squeeze(1)
a.shape, squeezed.shape

(torch.Size([2, 1, 10]), torch.Size([2, 10]))

In [22]:
# dois stacks com 2 linhas e 10 colunas cada
a = torch.ones(2,2,10)
print(f'a = {a}')
print(f'Formato de a = {a.shape}')

a = tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])
Formato de a = torch.Size([2, 2, 10])


In [31]:
# não muda nadaa
squeezed = a.squeeze(1)
print(f'squeezed = {squeezed}')
print(f'Formato de squeezed = {squeezed.shape}')

squeezed = tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])
Formato de squeezed = torch.Size([2, 2, 10])


In [32]:
# dois stacks com 3 linhas e uma coluna cada
a = torch.ones(2,3,1)
print(f'a = {a}')
print(f'Formato de a = {a.shape}')

a = tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]])
Formato de a = torch.Size([2, 3, 1])


In [34]:
# aqui sim alterou para apenas 1 stack
squeezed = a.squeeze(2)
print(f'squeezed = {squeezed}')
print(f'Formato de squeezed = {squeezed.shape}')

squeezed = tensor([[1., 1., 1.],
        [1., 1., 1.]])
Formato de squeezed = torch.Size([2, 3])


In [35]:
# 2 linhas e 3 colunas
a = torch.ones(2,3)
print(f'a = {a}')
print(f'Formato de a = {a.shape}')

# alterando para 2 stacks com 3 linhas e 1 coluna
squeezed = a.unsqueeze(2)
print(f'squeezed = {squeezed}')
print(f'Formato de squeezed = {squeezed.shape}')

a = tensor([[1., 1., 1.],
        [1., 1., 1.]])
Formato de a = torch.Size([2, 3])
squeezed = tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]])
Formato de squeezed = torch.Size([2, 3, 1])


In [36]:
# 2 linhas 3 colunas
a = torch.ones(2,3)

# usando None para criar dimensões no eixo especificado
print(a[None].shape)
print(a[:,None].shape)
print(a[:,:,None].shape)

torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3, 1])
