In [2]:
import numpy as np

Numpy Arrays

In [3]:
minha_lista = [1, 2, 3]

In [4]:
minha_lista

[1, 2, 3]

In [5]:
np.array(minha_lista) # Criando um array do numpy.

array([1, 2, 3])

In [6]:
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(minha_matriz) # Criando uma outra array no numpy, agora como matriz.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0, 10) # Função arange para criar um array sequencial.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0, 10, 2) # Definindo o passo do arange de 2 em 2 números.

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(3) # Criando um array de zeros

array([0., 0., 0.])

In [11]:
arr = np.zeros(3)

In [12]:
arr

array([0., 0., 0.])

In [13]:
arr = np.zeros((5, 5)) # Criando uma array matriz de zeros.

In [14]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((3, 3)) # Criando uma array matriz de 1.

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.eye(4) # Matriz identidade, define apenas o número de linhas e colunas (identidade é sempre uma matriz quadrada)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.linspace(0, 10, 2) # Linspace define um array com o mesmo espaçamento entre os elementos.

array([ 0., 10.])

In [18]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [19]:
np.random.rand(5) # Random contem vários métodos para gerar números aleatóriamente, nesse caso um array de 5 números aleatórios.
# Rand define números uniformemente distribuidos, ou seja, eles tem a mesma chance de serem escolhidos.

array([0.76055898, 0.19838401, 0.15215497, 0.40559264, 0.82703742])

In [20]:
np.random.rand(5) * 100

array([31.03061447, 69.13378216, 93.68756676, 50.70316932, 61.55813174])

In [21]:
np.random.rand(5, 4) # Aqui um array matriz de números aleatórios

array([[0.5836652 , 0.92310565, 0.39162544, 0.22142816],
       [0.04283189, 0.49049561, 0.74612179, 0.17016872],
       [0.29673083, 0.71319549, 0.08684032, 0.1262158 ],
       [0.03675713, 0.89093751, 0.63098314, 0.54038777],
       [0.96678623, 0.24592863, 0.25874638, 0.61447236]])

In [22]:
np.random.rand(5, 4, 3) # Aqui seria como um objeto 3d, pois possui uma terceira dimensão invés de 2 como em uma matriz.

array([[[0.19999151, 0.7384138 , 0.72291755],
        [0.66570016, 0.08030989, 0.83994134],
        [0.52923108, 0.62443415, 0.56994746],
        [0.67056868, 0.98337829, 0.23963465]],

       [[0.48888506, 0.95506288, 0.22417817],
        [0.52042645, 0.14792919, 0.29004637],
        [0.89076526, 0.70651259, 0.23580479],
        [0.88362064, 0.44098661, 0.93203796]],

       [[0.41254424, 0.74803601, 0.43897691],
        [0.93730126, 0.34965487, 0.50347025],
        [0.23839752, 0.90064546, 0.20226495],
        [0.17764999, 0.60575321, 0.54613768]],

       [[0.37144933, 0.45909702, 0.71425926],
        [0.17816373, 0.2337026 , 0.59373702],
        [0.21270645, 0.90974508, 0.76708652],
        [0.82599958, 0.24674271, 0.54402824]],

       [[0.80296424, 0.21360791, 0.12124634],
        [0.26716613, 0.12794344, 0.1728456 ],
        [0.56643141, 0.88687908, 0.66252664],
        [0.45878589, 0.99853121, 0.27759369]]])

In [23]:
np.random.randn(4) # RandN faz uma distribuição aleatória normal.

array([-0.45495032,  1.0778122 , -0.80727505,  0.54290323])

In [24]:
np.random.randint(0, 100, 10) # Números aleatórios Inteiros

array([58, 77, 38, 77, 12, 35,  8, 61, 26, 87])

In [25]:
np.round(np.random.rand(5) * 100, 0) #Função round serve para arredondar números quebrados, obtendo assim um resultado parecido com o anterior

array([43., 93., 52., 98., 62.])

In [26]:
arr = np.random.rand(25)

In [27]:
arr

array([0.75356356, 0.95564191, 0.54612177, 0.13134669, 0.10892274,
       0.3862829 , 0.56207518, 0.07202096, 0.93315119, 0.3105511 ,
       0.3116381 , 0.68479702, 0.72605453, 0.72163181, 0.94774117,
       0.65824815, 0.31537036, 0.37925788, 0.37619955, 0.3436538 ,
       0.24927313, 0.28683732, 0.35959885, 0.54692966, 0.65310663])

In [28]:
arr.reshape((5,5)) # Reshape serve para ajustar o formato do array, nesse caso transformando uma lista em uma matriz.

array([[0.75356356, 0.95564191, 0.54612177, 0.13134669, 0.10892274],
       [0.3862829 , 0.56207518, 0.07202096, 0.93315119, 0.3105511 ],
       [0.3116381 , 0.68479702, 0.72605453, 0.72163181, 0.94774117],
       [0.65824815, 0.31537036, 0.37925788, 0.37619955, 0.3436538 ],
       [0.24927313, 0.28683732, 0.35959885, 0.54692966, 0.65310663]])

In [29]:
arr.shape # Mostra o formato atual do array

(25,)

In [30]:
arr.max() # Acha o maior valor do array

0.9556419131644996

In [31]:
arr.min() # Acha o menor valor do array

0.07202095784641249

In [32]:
arr.argmax() # Acha o index do maior valor

1

In [33]:
arr.argmin() # acha o index do menor valor

7

Numpy Indexação

In [34]:
arr = np.arange(0, 30, 3)

In [35]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [36]:
arr[3] # Referencia o valor que está no index 3 (começa em 0)

9

In [37]:
arr[2:5] # Referencia a lista de elementos entre começando no index 2, e mostra até o index 4 (index 5 não é mostrado)

array([ 6,  9, 12])

In [38]:
arr[:5] # Do 0 até o 4

array([ 0,  3,  6,  9, 12])

In [39]:
arr[2:] # Do index 2 até o último

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [40]:
arr[2:] = 100 # Alterando o valor de toda a lista de elementos que vai do index 2 até o final

In [41]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [42]:
arr = np.arange(50).reshape((5, 10)) # Criando um array de 0 até 49 e mudando o formato para uma matriz.

In [43]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [44]:
arr.shape # Pegando o formato

(5, 10)

In [45]:
arr[1:][:] # Pegando um pedaço da matriz (linha de index 1 até o final, todas as colunas)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [46]:
arr2 = arr[:3].copy() # Usando a função para copiar uma parte do outro array (Por padrão ele apenas referencia como um ponteiro invés de 
# fazer uma cópia)

In [47]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [48]:
arr2[:] = 10 # Definindo todos os valores do array como 10

In [49]:
arr[1:4,5:] # Outra forma de puxar uma parte da matriz, agora com uma vírgula fazendo a separação invés de 2 conchetes diferentes

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39]])

In [50]:
bol = arr > 30 # Criando uma matriz com valores de verdadeiro ou falso para caso a condição seja satisfeita para o número da posição

In [51]:
bol

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [52]:
arr[bol] # Recriando o array, mas agora apenas com os valores que eram verdadeiros (só funciona se as duas matrizes tiverem o mesmo tamanho)

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

Numpy operações

In [53]:
arr = np.arange(0, 16)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [55]:
arr + arr # Soma de arrays, soma elemento por elemento

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [56]:
arr - arr # Mesma coisa, mas agora com subtração

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
arr * arr # Mesma coisa com a multiplicação.

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [58]:
arr / arr # Mesma coisa com a divisão, o único motivo de estar aparecendo um erro é por causa da tentiva de fazer uma divisão por 0

/tmp/ipykernel_144522/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [59]:
arr ** 2 # Pontenciação para cada elemento (eleva cada elemento ao quadrado)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [60]:
arr + 100 # Soma escalar (soma cada elemento o valor passado)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [61]:
arr - 100 # Subtração escalar

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85])

In [62]:
arr * 100 # Multiplicação escalar

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500])

In [63]:
np.sqrt(arr) # Calcula a raiz quadrada de cada um dos elementos.

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [64]:
np.exp(arr) # Calcula o valor exponencial de cada elemento

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [65]:
np.mean(arr) # Calcula a média de todos os elementos do array

7.5

In [66]:
np.std(arr) # Calcula o desvio padrão do array

4.6097722286464435

In [67]:
np.sin(arr) # Calcula o seno de cada um dos elementos

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [68]:
np.max(arr) # Acha o maior elemento do array

15

In [69]:
np.min(arr) # Acha o menor elemento

0

In [70]:
arr.max() # Também acha o maior elemento, mas agora como uma propriedade do array e não como uma função numpy

15

In [71]:
arr.min()# Também acha o menor elemento, mas agora como uma propriedade do array e não como uma função numpy

0