In [1]:
import numpy as np

In [2]:
# Criando um array de zeros
array = np.zeros(5)
array

array([0., 0., 0., 0., 0.])

In [3]:
# Criando uma matriz de uns
array = np.ones([5, 10])
array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [4]:
# Criando um array de 0 até 100 com passo de 10 em 10
array = np.arange(0, 101, 10)
array

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [5]:
# Criando uma matriz identidade
array = np.eye(5)
array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
array * 5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [7]:
# Criando uma matriz com os valores tendo a mesma distancia entre si
array = np.linspace(0, 100, 50)
array

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [8]:
# Arredondando os valores e transformando em uma matriz
array = array.round()

In [9]:
array = array.reshape(10, 5)
array

array([[  0.,   2.,   4.,   6.,   8.],
       [ 10.,  12.,  14.,  16.,  18.],
       [ 20.,  22.,  24.,  27.,  29.],
       [ 31.,  33.,  35.,  37.,  39.],
       [ 41.,  43.,  45.,  47.,  49.],
       [ 51.,  53.,  55.,  57.,  59.],
       [ 61.,  63.,  65.,  67.,  69.],
       [ 71.,  73.,  76.,  78.,  80.],
       [ 82.,  84.,  86.,  88.,  90.],
       [ 92.,  94.,  96.,  98., 100.]])

In [10]:
#Verificando o tamanho
array.shape

(10, 5)

In [11]:
#verificando qual o maior valor
array.max()

100.0

In [12]:
# Criando uma array apenas com os valores pares através de uma matriz de boolean
bol = array % 2 == 0
bol

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [13]:
array = array[bol]
array

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
        22.,  24.,  76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,
        94.,  96.,  98., 100.])

In [14]:
# Contando a quantidade de elementos
len(array)

26

In [15]:
#Transoformando em matriz novamente
array = array.reshape(2, 13)
array

array([[  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
         22.,  24.],
       [ 76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,  96.,
         98., 100.]])

In [16]:
# Pegando uma matriz com a raiz quadrada de cada um dos valores
np.sqrt(array)

array([[ 0.        ,  1.41421356,  2.        ,  2.44948974,  2.82842712,
         3.16227766,  3.46410162,  3.74165739,  4.        ,  4.24264069,
         4.47213595,  4.69041576,  4.89897949],
       [ 8.71779789,  8.83176087,  8.94427191,  9.05538514,  9.16515139,
         9.2736185 ,  9.38083152,  9.48683298,  9.59166305,  9.69535971,
         9.79795897,  9.89949494, 10.        ]])

In [17]:
#fazendo operação da matriz com ela mesma
result = array[0] - array[1]
result

array([-76., -76., -76., -76., -76., -76., -76., -76., -76., -76., -76.,
       -76., -76.])

In [18]:
# Criando uma matriz com elementos aleatórios
al = np.random.randint(-15, 15, size=(2, 13))
al

array([[-11,  14, -13,  -7,  -5,  -2,  -3,  -4, -14,   5,  10,  -4, -11],
       [ -8, -12,  -9,   4,   9,  12, -12,   7, -10,   2, -15,   5,  14]])

In [19]:
resultado = array + al
resultado

array([[-11.,  16.,  -9.,  -1.,   3.,   8.,   9.,  10.,   2.,  23.,  30.,
         18.,  13.],
       [ 68.,  66.,  71.,  86.,  93.,  98.,  76.,  97.,  82.,  96.,  81.,
        103., 114.]])

In [20]:
# Calculando a média desses valores
resultado.mean()

47.76923076923077

In [21]:
# Calculando o desvio padrão dos elementos
resultado.std()

41.26397916259847